// Generated by CoffeeScript 1.10.0
var toggle;

toggle = function(link) {
  var i, ul;
  i = $(link).prev();
  ul = $(link).next();
  while (ul.prop('nodeName') !== 'UL') {
    ul = ul.next();
  }
  if (ul.css('display') === 'none' || ul.css('display') === null) {
    ul.css('display', 'block');
    i.removeClass("glyphicon-chevron-right").addClass("glyphicon-chevron-down");
  } else {
    ul.css('display', 'none');
    i.removeClass("glyphicon-chevron-down").addClass("glyphicon-chevron-right");
  }
  return true;
};
