// Generated by CoffeeScript 1.10.0
$(function() {
  var IPinfo, displayIP, onDataReceived;
  IPinfo = {
    ip: '::1',
    hostname: 'localhost'
  };
  onDataReceived = function(data) {
    return IPinfo = data;
  };
  displayIP = function() {
    $('#userAgent').html(navigator.userAgent);
    return true;
  };
  displayIP();
  return true;
});
